name: test-cepler-action
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: cepler
        uses: bodymindarts/cepler-action@main
        with:
          environment: testflight
      - name: Needs deploying:
        run: echo "The time was ${{ steps.cepler.outputs.needs_deploying }}"
