name: test-cepler-action
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bodymindarts/cepler-action@main
        with:
          environment: testflight
