name: test-cepler-action
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - id: cepler
        uses: bodymindarts/cepler-action@main
        with:
          environment: testflight
          prepare: true
      - if: ${{ steps.cepler.outputs.needs_deploying == 'true' }}
        name: Deploy
        run: echo "The time was ${{ steps.cepler.outputs.needs_deploying }}"
      - if: ${{ steps.cepler.outputs.needs_deploying == 'true' }}
        uses: bodymindarts/cepler-action@main
        with:
          environment: testflight
          record: true
      - if: ${{ steps.cepler.outputs.needs_deploying == 'true' }}
        run: |
          git pull --rebase
          git push
